CREATE TABLE "run" 
( 
    [RunId] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    [Name] NVARCHAR(128) NOT NULL
);

CREATE TABLE "suite" 
( 
    [SuiteId] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    [Name] NVARCHAR(128) NOT NULL
);



